# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='daily_request_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_request_ts',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 7, 6, 36, 19, 97510, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
