# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20170907_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='total_request_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='daily_request_counter',
            field=models.IntegerField(default=0),
        ),
    ]
